### ISSUE TITLE
need to install tibble from source

### ISSUE THREAD

**Issue by jzook** [Illumina/happyR#3]
When I tried to install happyR on my mac, I got the error below.  After install tibble from source, then it worked - is that what you'd expect?

> devtools::install_github("Illumina/happyR")
Downloading GitHub repo Illumina/happyR@master
from URL https://api.github.com/repos/Illumina/happyR/zipball/master
Installing happyR
Skipping 1 unavailable package: tibble
Installing 5 packages: assertthat, DBI, dplyr, lazyeval, Rcpp

  There are binary versions available (and will be installed) but the source versions are later:
           binary  source
assertthat    0.1   0.2.0
DBI         0.3.1     0.7
dplyr       0.4.3   0.7.4
lazyeval   0.1.10   0.2.1
Rcpp       0.12.3 0.12.13

'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/3y/53wm_96s59b33hcr5pypxd440017zz/T/RtmpCaw3IT/devtools1045b6d3f1abe/Illumina-happyR-4ef8832'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 

ERROR: dependency ‘tibble’ is not available for package ‘happyR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/happyR’
Error: Command failed (1)

**Comment by blmoore** [comment]
Thanks for reporting this. Looks like you might be running quite an old R version, can you post `sessionInfo()`?

**Comment by jzook** [comment]
You might be right:
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] happyR_1.0.0 tibble_1.3.4

loaded via a namespace (and not attached):
 [1] curl_0.9.6      devtools_1.10.0 digest_0.6.8    git2r_0.14.0    grid_3.1.2      httr_1.1.0      knitr_1.15.1   
 [8] memoise_1.0.0   R6_2.1.2        Rcpp_0.12.3     readr_0.2.2     rlang_0.1.2     tools_3.1.2     withr_1.0.1

**Comment by blmoore** [comment]
Thanks, I think updating your R version should fix the issue.`tibble` says it supports >= 3.1 but maybe there's some downstream dependency that doesn't...

**Comment by blmoore** [comment]
I'm going to close this as I'm pretty sure it was R version related but please reopen if still an issue!
