### ISSUE TITLE
AUC

### ISSUE THREAD

**Issue by ksw9** [Illumina/happyR#4]
I'm wondering a best way to calculate AUC from a pr_curve created in the happyR package?
Thank you!

**Comment by blmoore** [comment]
AuPR might not be very useful in this case — often just varying a quality cutoff won't span the entire range of recall so a good classifier could rank below a poor classifier whose PR curve is sampled along a broader range (e.g. caller 1 outputs variants with quality scores 30-60, caller 2 outputs them with 0-1000). If you still want to calculate this, there are various generic methods to integrate under a curve you could try.

The F<sub>1</sub> score as output by hap.py might be a more useful summary statistic.
